name: Maven Deploy Artifact

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: false
        default: "17"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
      mvn-args:
        description: 'Additional maven args'
        required: false
        type: string
      docker-registry:
        description: 'Docker registry'
        required: false
        default: 'ghcr.io'
        type: string
      registry-username:
        description: 'Username for image registry'
        required: true
        type: string
      dockerfile-path:
        description: 'Path to dockerfile directory'
        required: false
        default: './target'
        type: string
    secrets:
      registry-access-token:
        description: 'Access token for image registry'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: 'maven'

      - shell: bash
        run: |
          mvn -B clean compile package ${{ inputs.mvn-args }}

      - name: Log in to the Container registry
        uses: docker/login-action@f6d32ad0236599ffe0bb261e71184c3e4e1d47cd
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ inputs.registry-username }}
          password: ${{ secrets.registry-access-token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9b5093b231860810fe3ebe99b9372ef975604c49
        with:
          images: ${{ inputs.docker-registry }}/${{ github.repository }}
          tags: |
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@309fb9180f2030167151ad947584dc32f6164656
        with:
          context: ${{ inputs.dockerfile-path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}