name: Maven Build Artifact

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: false
        default: "17"
        type: string
      java-distribution:
        description: 'Java distribution'
        required: false
        default: "temurin"
        type: string
      mvn-args:
        description: 'Additional maven args'
        required: false
        type: string
      ignore-coverage:
        description: 'Ignore test coverage step'
        default: false
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: 'maven'
          server-id: github
          server-username: vitaxa
          server-password: ${{ secrets.CRASHTEAM_REPO_TOKEN }}

      - name: Check Maven settings
        run: grep "<server>" ~/.m2/settings.xml || true

      - shell: bash
        run: |
          mvn -s ~/.m2/settings.xml -B clean compile package ${{ inputs.mvn-args }}

  test-coverage:
    runs-on: ubuntu-22.04
    if: ${{ !inputs.ignore-coverage }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: 'maven'

      - shell: bash
        run: |
          mvn -B clean compile package ${{ inputs.mvn-args }}

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
